### ISSUE TITLE
Buggy networking example with laminar (issues/unoptimized)

### ISSUE THREAD

**Issue by tree786** [lowenware/dotrix#71]
Hallo

I have tried to incorporate the [laminar ](https://github.com/amethyst/laminar) networking lib into a very basic template dotrix scene. Although the basics are working (you can send a basic `String` as a vec of u8 bytes (using `.into_bytes()` method). However the current results are quite poor, due to my lack of understanding of how to properly integrate it . 
For example , the client successfully sends the given string to the server, and the server receievs it. However, there seems to be unpredictable delay between certain packets sent and received. I do not fully undertand the issue; is it because I am spawining a new thread each frame on the server (`let _thread = thread::spawn(move || socket.manual_poll(Instant::now()))`)? . I have attached both client and server (maybe you can see what the issue i am doing wrong is). You can run the server first (currently on address 127.0.0.1) by using `cargo run --release` on the `server` folder. Then run the client 
Here is my repo for the test project: [laminar-integrations](https://github.com/tree786/laminar-integrations)

Thanks

**Comment by Lowentwickler** [comment]
Hi!

First think you can do, is to move this into a startup system
```
let mut socket = Socket::bind(addr).unwrap();
```

and store the result into some your custom service (structure), so you won`t need to make an additional expensive system call (2 in fact, becase closing of the socket also happens when `client` function returns) on each frames. UDP communication (I believe it is UDP) that you use, should be fast enough for testing purposes. 

Then if you use a single thread and communicate in systems, it is worth to consider a non-blocking sockets. I haven't check if laminar offers something like this. Or alternatively you can move all the communication into a separate thread and synchronize it using non-blocking mutexes (I mean `try lock` concept).

Cheers

**Comment by tree786** [comment]
Hi, Thanks very much for info. I have created a struct to hold the Socket, but had issues with mutability references. However it now works well. I can send packets of data from client to server and vice versa. Cheers for replies ! :) 
I think I will now try to make multiplayer game with my car set up!

**Comment by tree786** [comment]
I will close now
